### ISSUE TITLE
5.7 support?

### ISSUE THREAD

**Issue by allochi** [concrete5/addon_internationalization#61]
Hi, Thanks for the add on, I just got a pre-setup Concrete5 hosting, and it turn out to be 5.7, any plans to upgrade the add on to support 5.7, I did try the current version of Internationalization, and Concrete5 complained about it.

Thanks again.

**Comment by fabian** [comment]
According to the [5.7.3 Release Notes](http://www.concrete5.org/documentation/developers/5.7/background/version-history/5-7-3-release-notes/) this add-on has been added to the core and is included by default.

**Comment by allochi** [comment]
@fabian Thank you very much for the answer, I was busy and I didn't check the replies. It turn out that I had 5.7.2.1, once I upgraded the multilingual section appeared.

Thanks again!
